import {
	CLAIM_MANIFEST_BUILDER_VERSION,
	CLAIM_MANIFEST_SCHEMA_VERSION,
} from "../claim-manifest/types";
import { FACT_LOCK_MANIFEST_INPUT_VERSION } from "../fact-lock/manifest-request-hash";
import {
	FACT_LOCK_MANIFEST_PROMPT_VERSION,
	FACT_LOCK_OUTPUT_SCHEMA_VERSION,
	FACT_LOCK_PROMPT_VERSION,
	FACT_LOCK_ZERO_CLAIM_PROMPT_VERSION,
} from "../fact-lock/types";
import {
	SCRIPT_CLAIM_REFRESH_INPUT_VERSION,
	SCRIPT_CLAIM_REFRESH_OUTPUT_SCHEMA_VERSION,
	SCRIPT_CLAIM_REFRESH_PROMPT_VERSION,
} from "../script-claim-refresh/runtime-types";
import {
	SCRIPT_OUTPUT_SCHEMA_VERSION,
	SCRIPT_PROMPT_VERSION,
	SCRIPT_SNAPSHOT_VERSION,
} from "../script-generation/policy";

export const CLAIM_SUBJECT_CURRENT_SCRIPT_INPUT_VERSION =
	SCRIPT_SNAPSHOT_VERSION;
export const CLAIM_SUBJECT_NEXT_SCRIPT_INPUT_VERSION =
	"script-input.v3" as const;

export const CLAIM_SUBJECT_CURRENT_SCRIPT_OUTPUT_SCHEMA_VERSION =
	SCRIPT_OUTPUT_SCHEMA_VERSION;
export const CLAIM_SUBJECT_NEXT_SCRIPT_OUTPUT_SCHEMA_VERSION =
	"script-draft.v3" as const;

export const CLAIM_SUBJECT_CURRENT_SCRIPT_PROMPT_VERSION =
	SCRIPT_PROMPT_VERSION;
export const CLAIM_SUBJECT_NEXT_SCRIPT_PROMPT_VERSION =
	"script-prompt.v3" as const;

export const CLAIM_SUBJECT_CURRENT_REFRESH_INPUT_VERSION =
	SCRIPT_CLAIM_REFRESH_INPUT_VERSION;
export const CLAIM_SUBJECT_NEXT_REFRESH_INPUT_VERSION =
	SCRIPT_CLAIM_REFRESH_INPUT_VERSION;
export const CLAIM_SUBJECT_CURRENT_REFRESH_PROMPT_VERSION =
	SCRIPT_CLAIM_REFRESH_PROMPT_VERSION;
export const CLAIM_SUBJECT_NEXT_REFRESH_PROMPT_VERSION =
	"script-claim-refresh-prompt.v2" as const;
export const CLAIM_SUBJECT_CURRENT_REFRESH_OUTPUT_SCHEMA_VERSION =
	SCRIPT_CLAIM_REFRESH_OUTPUT_SCHEMA_VERSION;
export const CLAIM_SUBJECT_NEXT_REFRESH_OUTPUT_SCHEMA_VERSION =
	"script-claim-refresh-output.v2" as const;

export const CLAIM_SUBJECT_CURRENT_MANIFEST_SCHEMA_VERSION =
	CLAIM_MANIFEST_SCHEMA_VERSION;
export const CLAIM_SUBJECT_NEXT_MANIFEST_SCHEMA_VERSION =
	CLAIM_MANIFEST_SCHEMA_VERSION;
export const CLAIM_SUBJECT_CURRENT_MANIFEST_BUILDER_VERSION =
	CLAIM_MANIFEST_BUILDER_VERSION;
export const CLAIM_SUBJECT_NEXT_MANIFEST_BUILDER_VERSION =
	"claim-manifest-builder.v2" as const;

export const CLAIM_SUBJECT_CURRENT_FACT_LOCK_MANIFEST_INPUT_VERSION =
	FACT_LOCK_MANIFEST_INPUT_VERSION;
export const CLAIM_SUBJECT_NEXT_FACT_LOCK_MANIFEST_INPUT_VERSION =
	"fact-lock.manifest.v2" as const;
export const CLAIM_SUBJECT_CURRENT_FACT_LOCK_MANIFEST_PROMPT_VERSION =
	FACT_LOCK_MANIFEST_PROMPT_VERSION;
export const CLAIM_SUBJECT_NEXT_FACT_LOCK_MANIFEST_PROMPT_VERSION =
	"fact-lock-manifest-prompt.v2" as const;
export const CLAIM_SUBJECT_CURRENT_FACT_LOCK_OUTPUT_SCHEMA_VERSION =
	FACT_LOCK_OUTPUT_SCHEMA_VERSION;
export const CLAIM_SUBJECT_NEXT_FACT_LOCK_OUTPUT_SCHEMA_VERSION =
	FACT_LOCK_OUTPUT_SCHEMA_VERSION;
export const CLAIM_SUBJECT_CURRENT_LEGACY_FACT_LOCK_PROMPT_VERSION =
	FACT_LOCK_PROMPT_VERSION;
export const CLAIM_SUBJECT_CURRENT_ZERO_CLAIM_PROMPT_VERSION =
	FACT_LOCK_ZERO_CLAIM_PROMPT_VERSION;
